puts "The students of my cohort at Makers academy"
puts "-------------------------------------------"
student_count = 19
#first we print the list of students:
puts "Steve Musgrave"
puts "Sroop Sunar"
puts "Colin Marshall"
puts "Josh Fail-Brown"
puts "Louise Lai"
puts "Robin Doble"
puts "Alex Wong"
puts "Scott Dimmock"
puts "Muhanad Al-Rubaiee"
puts "Shelley Hope"
puts "Will Hall"
puts "Oliver Delevingne"
puts "Nico"
puts "Apostolis"
puts "Stefania"
puts "Robert Leon"
puts "Emma Williams"
puts "Joey Wolf"
puts "Julie Walker"
#finally we print the total:
puts "Overall, we have #{student_count} great students."

