puts "The Students of my cohort at Makers Academy"
puts "-------------------------------------------"	
puts "David Beckham"
puts "David Tennant"
puts "Vincent Gallo"
puts "Colin Firth"
puts "Johnny Depp"
puts "Dan Ariely"
print "Overall, we have "
print 6
puts " great students"
